### ISSUE TITLE
Analysis : Test master vs develop branch behavior

### ISSUE THREAD

**Issue by jrmartin** [MetaCell/open-physiology-viewer#139]
@enicolasgomez We need to understand what has changed in the model. Our master branch has the latest code from the original repo, our develop branch doesn't have it. 

Currently, the auto layout is working as expected in the develop branch, but no on master. This is because the model has changed, we need to understand what changed.

**Comment by enicolasgomez** [comment]
- validateTemplate on each expandTemplate call has been added
- objects are now accessed by referenced (findResourceByID vs refToResource)
- special checks for Wire geometry
- createForceNodes has been added, possibly continuing their idea of programatically determing the objects positions by using additional forces
- groupTemplate model has been added as an abstraction layer over groups, introducing the namespace idea
- logging mechanism has been extended
- joinModel now does better management when trasversing models
- scaffoldModel extended load functionality, excel import export improvements
- scaffoldModel improved abstraction for update, instead of using util function
- collectNestedResources
- verticeModel update affected by reference access changes and group abstraction
- verticeModel replicateInternalNodes special lyphs tratement 
- autoLayout fixToTargetRegion changed evaluating source and target sizes
- autoLayout checking for non defined arrays of objects. Probably as consequence of the new join/merge abstraction.

@jrmartin I will crate an intermediate master-develop branch to attempt a merge given my latest understanding of the changes
