### ISSUE TITLE
Anti-aliasing

### ISSUE THREAD

**Issue by jrmartin** [MetaCell/open-physiology-viewer#17]
When rendering wires for the scaffolds the aliasing of the borders/arcs/lines becomes quite apparent. It would be nice to have those anti-aliased.

**Comment by jrmartin** [comment]
Hi @tgbugs,  I added a couple of screenshots showing the areas with the aliasing problem, please let us know if there's other areas of the map where you know the aliasing problem is noticeable. cc @ddelpiano

**Comment by jrmartin** [comment]
@ddelpiano Some objects are been rendered more than once, so there's a chance that they are fighting to be rendered one on top of each other. cc @enicolasgomez for more info

**Comment by ddelpiano** [comment]
are we sure the issue is the anti-aliasing here? below you can see 2 loads of the application, one without and one with anti aliasing, it seems clear to me that the anti-aliasing is doing the job.

![screenshot (11).png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/171619a5-bfb7-4e49-8fb4-911193b2eb8b)
![screenshot (12).png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/d645ec8d-25e8-412e-85b8-eb577e822adf)

on top of that I added an FXAA shader in feature/17, below example with and without.

![screenshot (14).png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/0020f646-e7e5-4cba-bddf-931658c365dc)
![screenshot (13).png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/95613d6a-276f-46d7-a981-3b1a1abbdfe9)

I checked this works, it's doing is job but the improvements are close to none imho.

@jrmartin could you post the images you mentioned above here in the card please? Thx

**Comment by ddelpiano** [comment]
@jrmartin as suggested I checked and the mesh is not rendered in the same spot multiple times, I manipulated the object itself at the end of the dragging (a single time) and increased the z coordinate to see if a sibling of the same node would have stayed in the TOO map but that is not the case as visible from the screenshot.

![screenshot (15).png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/fd405e98-fecf-4815-969c-232c72f207c7)
